name: at_bot
description: The @ platform bot in dart.
version: 1.0.0
homepage: https://www.atsign.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  at_client: ^3.0.7
  at_commons: ^3.0.2
  at_server_status: ^1.0.3
  crypton: ^2.0.3
  dotenv: ^3.0.0
  http: ^0.13.4
  intl: ^0.17.0
  nyxx: ^3.2.0
  nyxx_interactions: ^3.1.0
  nyxx_lavalink: ^3.0.0
  riverpod: ^1.0.3
  zxing_lib: ^0.5.0

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^1.0.0
  test: ^1.16.0
import_sorter:
  emojis: true
