name: Dart bot workflow

on:
  push:
    branches: [dart-trunk]
  pull_request:
    branches: [dart-trunk]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "2.14.3"
      # Fetch pub dependecies.
      - name: Install dependencies
        run: dart pub get
      # Verify formatting.
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      # Analyze the code.
      - name: Analyze project source
        run: dart analyze
      # Run unit tests.
      - name: Run tests
        run: dart test
